# coding=UTF-8
from __future__ import print_function, absolute_import, division
import six
import logging
from .method import resource_to_body

logger = logging.getLogger(__name__)


def wrap(content, title=u'Documentation'):
    return b''.join(s.encode('utf8') for s in [u'''<!doctype HTML>
    <html lang="en">
    <head>
        <title>Documentation for %s</title>
        <meta charset="UTF-8">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    </head>
    <body>
    <div class="container"> ''' % (title,)] + content + [
        u'</div> <p style="font-size: small">Generated by falcondocs</p></body></html>'])


def process(resources, docres):
    out = [u'<h1>Table of contents</h1><p style="margin-bottom: 30px;">']

    resources = [res for res in resources.get_resources() if res is not docres]
    resources.sort(key=lambda x: x.main_name)

    for res in resources:
        out.extend([u'<a href="#r%s">%s</a><br>' % (res.id, res.main_name)])

    out.extend([u'</p><hr>'])

    for res in resources:
        out.extend(resource_to_body(res))

    return out
